# Generated by Django 3.0.3 on 2020-07-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Buyername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Buyer')),
                ('Sellername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seller')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service')),
            ],
        ),
    ]
