# Generated by Django 3.0.3 on 2020-07-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seller')),
                ('servicename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service')),
            ],
        ),
    ]
