# Generated by Django 3.0.3 on 2020-07-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seller_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='Bio',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
